CREATE TABLE IF NOT EXISTS `IISLog` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `Date` date DEFAULT NULL,
  `Time` time DEFAULT NULL,
  `SiteName` varchar(50) DEFAULT NULL,
  `ComputerName` varchar(50) DEFAULT NULL,
  `SIP` varchar(50) DEFAULT NULL,
  `Method` varchar(50) DEFAULT NULL,
  `UriStem` varchar(255) DEFAULT NULL,
  `UriQuery` varchar(555) DEFAULT NULL,
  `Port` varchar(50) DEFAULT NULL,
  `CSUserName` varchar(50) DEFAULT NULL,
  `ClientIP` varchar(50) DEFAULT NULL,
  `CSVersion` varchar(50) DEFAULT NULL,
  `UserAgent` varchar(255) DEFAULT NULL,
  `Referer` varchar(255) DEFAULT NULL,
  `CSHost` varchar(50) DEFAULT NULL,
  `StatusCode` varchar(50) DEFAULT NULL,
  `SubStatusCode` varchar(50) DEFAULT NULL,
  `Win32Status` varchar(50) DEFAULT NULL,
  `TimeTaken` varchar(50) DEFAULT NULL,
  `XFF` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30874 DEFAULT CHARSET=latin1;